### ISSUE TITLE
[Feature Request] Config/JSON Custom Trophies

### ISSUE THREAD

**Issue by InjuredWolf** [svennieke/StatuesMod#1]
Would it be possible to allow users/modpack creators to add custom trophies for modded mobs? Not sure how easy/hard it would be to grab the models, but I dunno. Would be useful to set an item for each custom trophy to drop (like the blaze trophy does with its rods).
Is this at all possible?

**Comment by svennieke** [comment]
Honestly the way i am adding the statues, i don't think it will be possible to allow players to add custom statues, but if you want certain modded mobs to have statues support be sure to let me know those mods, i am planning to do modded mobs support to statues soon, which means i will add statues for mobs from other mods.

**Comment by InjuredWolf** [comment]
Well, Freezes from Tough As Nails would be great if you could add a trophy for them

**Comment by svennieke** [comment]
i will do my best to add them, but currently i am doing a little bit of rewriting stuff and still need to add a handful of vanilla mobs, but i will do my best to add this one as soon as i am done with the vanilla mobs :D

**Comment by InjuredWolf** [comment]
Sounds good. I await updates.
