### ISSUE TITLE
1.12.X-0.8.5.1 crashes dedicated server Forge 1.12.2 build 2707

### ISSUE THREAD

**Issue by kreezxil** [svennieke/StatuesMod#10]
Notes:
     on startup while looking for client side classes

crash report:
https://gist.github.com/c2618bcae20e0180cfba96f0b7dec6d0

fml server latest:
https://gist.github.com/f6a4c43bf22ebbca59504bf75a6a4083

Apparently your mod depends on Shadowfacts' Forgelin, because when I downgraded from their brand new release (1.7.1) to the previous release (1.6.0). The error stopped happening. If it is dependency can you add that to your overview?

If it is not a dependency then there is an issue between the two mods.

**Comment by Mrbysco** [comment]
I've tested a clean forge 2707 server with statues and theres no crashes there. So it must be some mod interaction
