### ISSUE TITLE
In 0.8.5.1 How can I get a Decorative Pufferfish Statues，the "PlayerCrafting=false"...

### ISSUE THREAD

**Issue by alkkhsl** [svennieke/StatuesMod#11]
In the "foolcraft3" the PlayerCrafting is false, but I need a Decorative Pufferfish Statues ,how can I get it ?
I can't find a mobs named "Pufferfish" .
also the Ghast Statues , I kill about 10K Ghast, there is no Ghast Statues drop..
ver:0.8.5.1

**Comment by Mrbysco** [comment]
Ghast statues can't be gotten in 0.8.5.1, it has been fixed in a newer version and is gonna be in foolcraft 3 v1.4.

Pufferfish... hmmmm... Maybe go fishing

**Comment by darkling2000** [comment]
Can you confirm version number where ghast drop was fixed? Just checking to see if my server has that version :)

**Comment by svennieke** [comment]
1.4.4 of Foolcraft or statues-1.12.X-0.8.6.jar if you look for the mod version

**Comment by darkling2000** [comment]
cool and yep can confirm working in version 0.8.6.3 as that is what my mod setting version is showing at in minecraft :) and I have managed to get both statues now. Thanks.
