### ISSUE TITLE
Server Crash statues-1.12.x-0.8.6.5

### ISSUE THREAD

**Issue by judicius** [svennieke/StatuesMod#13]
When updated to 0.8.6.5 server treats this as a client only mod and crashes. I was only able to discover this was the mod affecting the server by loading all other mods singly to see when the server crashed as it doesn't report in the log it was this mod specifically.

Crash Log: https://pastebin.com/9VKBcnHB

**Comment by Mrbysco** [comment]
I fixed this already but apparently the version I uploaded got lost.

**Comment by Mrbysco** [comment]
Reuploaded and tagged Curse on twitter to see if they can fix it
