### ISSUE TITLE
Crash on newest version

### ISSUE THREAD

**Issue by TheRealDadbeard** [svennieke/StatuesMod#14]
https://pastebin.com/mvkQG4KS

**Comment by Mrbysco** [comment]
Fixed in the new version. Sorry about that.

Apparently when I introduced the inventory rendering of the player statue I accidentally put the rendering somewhere that the server calls. And as the server can't render it crashed.

**Comment by Mrbysco** [comment]
I've uploaded a new release to curse

**Comment by Mrbysco** [comment]
https://minecraft.curseforge.com/projects/statues/files/2595312
