### ISSUE TITLE
Crash while ticking Entity, server can't start again

### ISSUE THREAD

**Issue by TheRealDadbeard** [svennieke/StatuesMod#16]
Just had a crash and it crashed the server completely and It wont start again

https://pastebin.com/MfHA58Vy

**Comment by Mrbysco** [comment]
What did you do before it crashed?

**Comment by TheRealDadbeard** [comment]
This is the problem. I have no idea. Asked around but nobody did anything with that mod. Made no statues etc.

Had to remove the mod as it would crash always the server at the end of loading.

**Comment by Mrbysco** [comment]
Found my issue.
While implementing the bit where you can use the statue as a player detector I messed up

**Comment by Mrbysco** [comment]
Will fix asap

**Comment by Mrbysco** [comment]
New release live at https://minecraft.curseforge.com/projects/statues/files/2599951
