### ISSUE TITLE
Looking a 'U'seable recipes in JEI causes crash in client

### ISSUE THREAD

**Issue by kreezxil** [svennieke/StatuesMod#17]
## Client Info
* Minecraft Version: 1.12.2

* Forge Version: 14..23.4.2747
* Mod Version: 1.12.x-0.8.6.10
* Java Version: 1.8.0_151

## Issue Description
With JEI open, while looking at items, when pressing 'u' to see useable recipes, the client crashes.

## Reproduce Steps
With JEI open, while looking at items, when pressing 'u' to see useable recipes, the client crashes.

## Additional Information
https://pastebin.com/9V0KDtgb

**Comment by Mrbysco** [comment]
related to https://github.com/svennieke/StatuesMod/issues/16 and fixed in next release

**Comment by kreezxil** [comment]
When is the next release?

**Comment by Mrbysco** [comment]
Uploading to curse right now

**Comment by kreezxil** [comment]
sweet, thanks.

**Comment by Mrbysco** [comment]
[Its live](https://minecraft.curseforge.com/projects/statues/files/2599951)
