### ISSUE TITLE
Spider statues don't drop?

### ISSUE THREAD

**Issue by Revvilo** [svennieke/StatuesMod#18]
## Client Info
* Minecraft Version: 1.12.2

* Forge Version: 14.23.4.2758
* Mod Version: 0.8.6.11
* Java Version: 181

## Issue Description
Spider statues seem to have been added, but don't drop.
We've been trying to get one on my Foolcraft 3 server for a long time, probably killing thousands.
I've looked through the changelogs and see that you have added them around 6.8 or so, but no code to handle the dropping of the statue seems to have been added.
Was this is just a mistake or is the statue not finished yet?

## Reproduce Steps
n/a

## Additional Information
n/a

**Comment by Mrbysco** [comment]
I think it might be my fault.
I was so obsessed with getting the player statue rendering in the inventory that I forgot to check if the statue dropped.

**Comment by Revvilo** [comment]
Not a worry at all. Although now the spiders better prepare themselves for the next FC3 release. 😉
Appreciate it!

**Comment by Mrbysco** [comment]
Uploaded to curse. Awaiting approval
