### ISSUE TITLE
Add config option to disable fake mobs from spawning

### ISSUE THREAD

**Issue by DWX12** [svennieke/StatuesMod#19]
## SUGGESTIONS
- [ ] I would like to propose new content.
- [x] I would like to propose changes.
- [ ] I would like to propose another thing.

I'm getting fake mobs spawning and would like an option to disable them in the config.

This is a great mod. Thank you for your time and effort and for contributing to the community.

<!-- SUGGESTIONS INFORMATION - Please explain what you want changed/added and why.
## SUGGESTION INFORMATION

**Comment by svennieke** [comment]
Do you mean the ones that currently spawn in the wild or the ones being spawned from the statues itself?

**Comment by Mrbysco** [comment]
Next version has a config option to disable the halloween event.
Also I redid the Fake Mob spawning. So you shouldn't really notice the fake mobs too much.
Before I messed up and they spawned waaaay to much.

**Comment by HenryLoenwind** [comment]
Just one more thing: We've been getting bug reports about our recipes not working because people captured fake mobs and didn't see any difference to real ones. So please name the entities correctly and fake their name with a TOP/WAILA plugin instead. Thank you.

**Comment by Mrbysco** [comment]
Blame @svennieke :P It was her idea not to name them fake :P
