### ISSUE TITLE
Weird server crash

### ISSUE THREAD

**Issue by ghost** [svennieke/StatuesMod#20]
## Client Info
* Minecraft Version: 1.12.2

* Forge Version: 1.12.2 (Modded) forge-14.23.5.2776
* Mod Version: 1.12.X-0.8.6.15
* Java Version: Java 8

## Issue Description
Server crash from MagicHandler 

## Reproduce Steps
not sure as I have no clue what causes it to happen on the server

## Additional Information
https://pastebin.com/yfqVeShk

**Comment by svennieke** [comment]
Which modpack are you using?

**Comment by TacticalUniverse** [comment]
Beyond The Void 2 @svennieke, its one of our custom packs

**Comment by Mrbysco** [comment]
Pastebin expired and user has been removed. Closing issue
