### ISSUE TITLE
[Bug] Statues unlocalized names showing in inventory & JEI

### ISSUE THREAD

**Issue by xGarionx** [svennieke/StatuesMod#21]
## Client Info
* Minecraft Version: 1.12

* Forge Version: 14.23.5.2815
* Mod Version: 0.8.7.1
* Java Version: 1.8.0_171

## Issue Description
Hi svennieke, currently i work on the modpack the acient cake and why looking for issues i stumbled across a bug in statues showing thier non localized names, i was wondering if i did some settings wrong, i can fix this of course by using content tweaker and add the correct discription, but anyway i wanted to make sure to report it.
I made 100% sure that the special drop system for certain persons is in place, so it cant be that.(died laughing when i actually saw that)

## Reproduce Steps
Look up items with jei.

## Additional Information
https://minecraft.curseforge.com/projects/the-ancient-cake
Imgur Pictures : https://imgur.com/a/uyUUIDm

**Comment by svennieke** [comment]
Hello is this issue happening in the latest version that can be found on curse of your modpack? if it is i will take a look at it tomorrow in the modpack itself so we can find where the issue is. And i must say you get my interest already regarding the Lucky players ;) glad i could make someone laugh with it

**Comment by xGarionx** [comment]
I loved the joke xD.
And yes the issue is in the last and the current (today ) uploaded version, since the pack is near its completion i started to do performance busting and review all recipes and stumpled across it, i would really appreciate if you take a look . Thanks :)

**Comment by Mrbysco** [comment]
Found the issue. Uploaded a new version to Curse.
