### ISSUE TITLE
Baby zombie statues does not show drops in JEI

### ISSUE THREAD

**Issue by DWX12** [svennieke/StatuesMod#24]
## Client Info
* Minecraft Version:
1.12.2
* Forge Version: NA
* Mod Version: 8.8.1
* Java Version: NA

## Issue Description
Under statue loot in JEI, baby zombie statues have no loot shown even though they have a chance to drop rotten flesh and an iron nugget.

## Reproduce Steps
Look at statue loot in JEI and compare it to the loot received by the baby zombie statue.

**Comment by svennieke** [comment]
![image](https://user-images.githubusercontent.com/7694658/58795580-558b7880-85fb-11e9-8488-42bf09f56288.png)
 It seems to work, can you please double check this?

**Comment by DWX12** [comment]
Okay then....if I had only taken a screenshot when it had happened. No clue what was going on then, but it indeed shows up, so I will close this issue. Very strange.
