### ISSUE TITLE
More sheep functionality

### ISSUE THREAD

**Issue by DWX12** [svennieke/StatuesMod#25]
## SUGGESTIONS
- [ ] I would like to propose new content.
- [x] I would like to propose changes.
- [ ] I would like to propose another thing.

<!-- SUGGESTIONS INFORMATION - Please explain what you want changed/added and why.
## SUGGESTION INFORMATION

**Comment by DWX12** [comment]
(Sorry, I have no clue how to use markdown information, so I'm replying to my comment instead)

Right now there's a sheared sheep and a sheep for every color; however, they aren't interchangeable. What I'm proposing is being able to interact with the sheep trophies with certain items in order to change them into their various varieties.

Use shears on a regular sheep statue to remove the correct colored wool from it and transform it into a sheared sheep. Likewise, interact with it using any colored wool to transform it into a unsheared sheep of that color. Obviously it would use one piece of wool to transform it and return one piece of wool when sheared.

In addition to that suggestion, I feel the mooshroom statue should have the same functionality as it is a vanilla feature. If you shear a mooshroom, you get a regular cow. I feel that this would just a one way transformation as it is in vanilla.

Similar ideas would be interacting with wolf and ocelot statues to transform them into their pet counterparts. Pet wolves, or dogs, would have collars that could be colored by interacting with them using dye. Maybe using different types of fish on the ocelot statue would transform them into their different textured varieties.

Just a few ideas to think about. Many thanks again.

**Comment by svennieke** [comment]
Sheeps should already be able to be changed with right clicking a dye on the statue when placed in the world (think it needs to be a decorative statue)

Regarding the mooshroom thing i feel like this would annoy some people if you accidently remove the mushrooms could be a big hassle for players.

Wolf and occelot statues don't exist yet ;) cats are definitly planned already but they will be the 1.14 varient

**Comment by DWX12** [comment]
I didn't know that with the sheep statues. I will have to try it out next time I play around with this mod.

Yeah, I can understand the mooshroom thing and guess I didn't think it through enough.

Glad to hear about the plans for pet statues. I suppose baby variants of most statues are planned as well?

**Comment by svennieke** [comment]
At this current time i don't know if baby versions are planned, if we add them it will be after the release
