### ISSUE TITLE
[Suggestion] Config option to disable mobs spawning from statues

### ISSUE THREAD

**Issue by DWX12** [svennieke/StatuesMod#26]
## SUGGESTIONS
- [ ] I would like to propose new content.
- [x] I would like to propose changes.
- [ ] I would like to propose another thing.

<!-- SUGGESTIONS INFORMATION - Please explain what you want changed/added and why.

**Comment by DWX12** [comment]
Would like to see a config option to turn off the ability to summon mobs when clicking on functional and above statues. Maybe even an option to change the chance of the mob spawning from each or all statues (all would probably be easier).

**Comment by svennieke** [comment]
There won't be a option to turn off the mobs from spawning from a statue, if you want to prevent a mob from spawning you should upgrade it to a peacefull statue

**Comment by DWX12** [comment]
Looking through this as the eyes of a pack developer. Wanting to prevent players from spawning mobs using the statues rather than as a player not wanting to spawn mobs. I was able to get roughly five or so mobs even before the timer refreshed for drops. So please reconsider this option.

**Comment by svennieke** [comment]
the mobs that spawn (or at least most of them) don't drop anything and should not be able to benefit the player in any way, an alternative that i can recomend for pack makers is to disable the recipes of the functional statues via craft tweaker and change the recipe of the peacefull ones, else the mod would have 2 peacefull statues with one being more end game to craft, and the requirement to mute a statue would be to make it peacefull first, meaning that players would need to craft a entire quite expansive tier just to mute the statue, i don't think this is a good idea, sorry

**Comment by DWX12** [comment]
An option for it would be nice, but that's just something I'm going to have to work with though. It's just easy to spawn a whole bunch of a mob within a short time. I'm certain that an auto-clicker of sorts could easily make a mob farm using the statues too.

Thanks for the replay and feedback.
