### ISSUE TITLE
Game crashes with statue that had been in place over a month.

### ISSUE THREAD

**Issue by mactso** [svennieke/StatuesMod#28]
Here's the pastebin.
https://paste.dimdev.org/ayeqawadir.mccrash

## Client Info
* Minecraft Version:
1.12.2
* Forge Version:   Launched Version: 1.12.2-forge1.12.2-14.23.5.2836 
* Mod Version:  https://www.curseforge.com/minecraft/modpacks/magiculture-2/files/2689014
* Java Version:   Java Version: 1.8.0_51, Oracle Corporation

## Reproduce Steps
Have a statue with that name.  Move to a place where the game tries to render it.  It doesn't crash immediately but the graphics turn flickery.   The statue has been in place for weeks (months?) without issue.  The problem started between 4am and 3pm today (7/18/2019) CST.

https://paste.dimdev.org/ayeqawadir.mccrash

## Additional Information

Issue resolved by deleting statue.  Other statues are fine.
I speculate that the user deleted or changed the skin today.

I checked and my last windows update was on 7/10 .. about 9 days ago.

**Comment by Mrbysco** [comment]
This is not my issue. You're not using our statues you're using Lemonz statues version https://github.com/Lemonszz/statues/issues

**Comment by mactso** [comment]
Oh thanks!  I'll move this over there.
