### ISSUE TITLE
crash from bad block render blaze statues

### ISSUE THREAD

**Issue by IchigoGames** [svennieke/StatuesMod#3]
minecraft 1.12.1
statues-1.12.X-0.7.3.1
Forge 2479
crash report https://pastebin.com/yszpbG0j
had a blaze statue in front of glass from applied energistics quartz glass and illuminated quartz glass
not sure if it happens with other glass but haveing the blaze statue in front of that glass made me crash could also have to do with me using sphax purebdcraft and optfine as soon as i removed the blaze statue the crash stop.

**Comment by Mrbysco** [comment]
I see you're using shaders. I've been able to reproduce the crash with the same shaders.
Can't seem to reproduce it when shaders are disabled.

Are you sure this only happens with Statues? and not with any other light emmiting not full block?

**Comment by IchigoGames** [comment]
it seems like its a shader + statues + ticking block aka applied energistics quartz glass and illuminated quartz glass issue so its probly not something that can be fixed on your side so ill close this
