### ISSUE TITLE
Functional Villager recipe uses Sound Snow Man statue, instead of Sound Villager Statue

### ISSUE THREAD

**Issue by JaSpr** [svennieke/StatuesMod#4]
![image](https://i.imgur.com/uy7x0zI.png?2)

**Comment by Mrbysco** [comment]
Which version of MC and which Statues version are you using?

**Comment by JaSpr** [comment]
That's a good question!

MC 1.10.2
Statues 1.10.2-0.7.3.2

**Comment by Mrbysco** [comment]
Will look into it, Will probably fixed together with the upcoming update.
