### ISSUE TITLE
Dedicated Server crash on version 0.8 (1.10.2)

### ISSUE THREAD

**Issue by JoelZBub** [svennieke/StatuesMod#5]
Server crashes with exception from Statues mod.
Mod version : 0.8 -1.10.2
Forge version : 12.18.3.2511
Java 8

Crash caused by NoClassDefFoundError (Client Render)
Here is crash report from server:
https://pastebin.com/thR02c1c

**Comment by Mrbysco** [comment]
I'll get right on it!

**Comment by Mrbysco** [comment]
Issue has been fixed and 0.8.1 has been uploaded to Curse.
It will be available after it has been approved.
Thanks for reporting.

-Mrbysco

**Comment by JoelZBub** [comment]
Thank you!

**Comment by Mrbysco** [comment]
It's approved and live on curse/curseforge
