### ISSUE TITLE
[BUG?] Fences connect to statues as if they were full blocks.

### ISSUE THREAD

**Issue by Forabor** [svennieke/StatuesMod#6]
Modpack: EggBlock ;
   Minecraft Version: 1.12.2 ;

Modname: StatuesMod ;
   Mod Version: 0.8.1 ;

Bug :   --See Title ;
Reproducible: Yes with all statues that i tested.

![2018-01-04_19 22 21](https://user-images.githubusercontent.com/8454481/34590421-a5af069a-f184-11e7-8b84-94df2281e7bb.png)

**Comment by Forabor** [comment]
If it matters they also connect to _Binnie's Extra Trees_ fences.

**Comment by Mrbysco** [comment]
If they connect to normal fences ofc they connect to modded fences :P

**Comment by Mrbysco** [comment]
I'll look into it

**Comment by Mrbysco** [comment]
Fixed next release. Sorry for waiting so long.
