### ISSUE TITLE
[Suggestion]: 

### ISSUE THREAD

**Issue by Yourname942** [svennieke/StatuesMod#77]
### General Info

- [ ] I would like to propose new content
- [X] I would like to propose changes
- [ ] I would like to propose another thing

### Suggestion Description

Instead of you having to manually add modded mobs to this mod, why not just allow us to hook into the code to add it ourselves using the modded mob's models as the statues? Or even better, just automatically do this for each model. Thank you!

**Comment by ShyNieke** [comment]
beacuse I enjoy making the models and textures, it actually allows me to improve my skills.

I do get why you are asking this and I can see if we can add something for missing statues until I get around to making them myself :)

**Comment by Yourname942** [comment]
I mean I didn't know if it was a lot of work for you/something that would take quite a lot of time/you would constantly have requests to add _x mod's mobs_. But If you are up for that, then by all means :) 

By having "default model" statues, it at least allows the end user to have a statue while you are able to create the final product. (removing any downtime)

**Comment by Mrbysco** [comment]
We're not planning on adding mod support to statues, maybe on a per mod basis as a separate addon mod once Statues is 100% complete
