### ISSUE TITLE
Dropped player statues don't have a skin.

### ISSUE THREAD

**Issue by TheRealDadbeard** [svennieke/StatuesMod#8]
Title. 1.12.2 on newest version available. Someone dropped their Player statue but the Skin is just default Steve but it is named right.

**Comment by Mrbysco** [comment]
The Player Statue item uses a placeholder model. It never had the skin in the inventory.
I'll look into having the skin show in inventory.

**Comment by TheRealDadbeard** [comment]
I have no skin when placing the statue. That's what i meant

Am 16.03.2018 13:30 schrieb "Mrbysco" <notifications@github.com>:

**Comment by svennieke** [comment]
the issue is that Mojang recently changed where they get the skins from, this issue will be fixed soon in the mod, i am sorry for the trouble

**Comment by TheRealDadbeard** [comment]
All fine. Wasn't sure if it was an issue on your side or them.

Am 16.03.2018 4:42 nachm. schrieb "svennieke" <notifications@github.com>:

**Comment by Henri1992** [comment]
1.10.2 also has the issue, I do not know if that is still maintained?

**Comment by Mrbysco** [comment]
A release has been uploaded to Curse/Curseforge which fixes this issue. (for 1.12.2)
