### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Leona1404** [svennieke/StatuesMod#81]
### General Info

- [X] I am running a modpack
- [X] I can reproduce this issue consistently in single-player
- [ ] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [X] I am crashing and can provide my crash report(s)
- [ ] I am using the latest version of the mod

### Forge version

43.2.0

### Minecraft version

1.19.2

### Mod version

0.3.2.1

### Java version

java 8

### Issue Description

upgraded a statue, Endermen Statue, with mobkilling 2, placed it and spawned a few endermen.
ca 5-10 sec after placing the statue with mobkilling 2, mc hardcrashes.
[crash-2023-03-12_22.29.40-server.txt](https://github.com/ShyNieke/StatuesMod/files/10961704/crash-2023-03-12_22.29.40-server.txt)

### Additional Information

[crash-2023-03-12_22.17.53-server.txt](https://github.com/ShyNieke/StatuesMod/files/10961709/crash-2023-03-12_22.17.53-server.txt)

**Comment by Mrbysco** [comment]
Fixed in the next version 0.3.3.2 which has been uploaded to CurseForge and should be available shortly

**Comment by Leona1404** [comment]
Thank you alot :3
