### ISSUE TITLE
[Suggestion]: How-to information

### ISSUE THREAD

**Issue by dragonwarrior00** [svennieke/StatuesMod#85]
### General Info

- [X] I would like to propose new content
- [ ] I would like to propose changes
- [X] I would like to propose another thing

### Suggestion Description

I would like to suggest a couple of things. In DireWolf20 1.19 mod pack, to get started with statues was difficult. I actually had to go digging through other forums to find a comment on how to turn a statue into the version you can level so you can get the  statue look. The information statue does not include any helpful information on how to start and how to level statues. Thus I find it useless really. Another suggestion, provide a list of the mob types to kill to allow the player level the statue on the Curseforge description section or at least for the special trophies (ie. Wasteland Pig statue) include this. Finally,  (if possible) wall shelves that the statues can sit on as well. Double stack statues just appear to be floating.

**Comment by Mrbysco** [comment]
In the latest version that's on CurseForge there's better information in the Patchouli book, There's also the wiki page on this Github https://github.com/ShyNieke/StatuesMod/wiki/Upgrading

**Comment by ShyNieke** [comment]
Suggestion 1: Have you used the informative statue (the one you can craft) and if you did did you right click it with a book to get the Patchouli book?

Suggestion 2: Currently there is no mobs for the special statues to level them up, this is a oversight and will be fixed in future versions

Suggestion 3: Wall shelves are currently not planned, that said if you do have suggestions on how they would look I can reconsider it but right now it feels like to me that using trapdoors and slabs in buildings makes more sense instead of adding a shelf. 

Edit: for future suggestions/bug reports it's easier to open multiple tickets one for each issue/suggestion instead of putting them all in one (easier to read and manage)

**Comment by dragonwarrior00** [comment]
> Suggestion 1: Have you used the informative statue (the one you can craft) and if you did did you right click it with a book to get the Patchouli book?
> 
> Suggestion 2: Currently there is no mobs for the special statues to level them up, this is a oversight and will be fixed in future versions
> 
> Suggestion 3: Wall shelves are currently not planned, that said if you do have suggestions on how they would look I can reconsider it but right now it feels like to me that using trapdoors and slabs in buildings makes more sense instead of adding a shelf.
> 
> Edit: for future suggestions/bug reports it's easier to open multiple tickets one for each issue/suggestion instead of putting them all in one (easier to read and manage)

Thanks for replying.

1. I didn't even know that was a possible. JEI didn't show how to get the book. Left or right click in JEI didn't work. The S.T.A.T.U.E JEI didn't show anything as well. The book did become available but very limited info. The GitHub info from Mrbysco is very nice. Transcribing the info to the book would be nice.

2. Glad for the updated info. I was carrying the Wasteland Pig for 2 months in my inventory to see if by chance I could get a mob kill to register. Now it is on display.

3. Ya trapdoor and slabs could always work. Since the Statue Display in the pack as a decorative item that seems more like a block to put on the ground for displaying. Wall shelve version would allow more flexibility on where statues could be located while still using an item from the mod pack.  Design version could be like the Statue Display look to keep it in the same theme for the pack.

**Comment by dragonwarrior00** [comment]
> In the latest version that's on CurseForge there's better information in the Patchouli book, There's also the wiki page on this Github https://github.com/ShyNieke/StatuesMod/wiki/Upgrading

Thanks for the info. This is very nice and informative.

**Comment by ShyNieke** [comment]
The new info should be in the book already in newer versions of the mod, I think the Direwolf 20 pack is using an outdated version of the mod. 

Good that you mentioned that you didn't know it was possible while I am unsure about how we add stuff to JEI (bysco does the code stuff) I do know how to make advancements and will make an advancement for it (just like how there is an advancement for the informative statue)

I appreciate the feedback in regards of the wall shelves, and while my own focus is currently on adding new statues (Need to get all vanilla mobs in some day haha) I can ask Douwsky if he would be interested in making a wall shelf, as he made the original display stand to :)

**Comment by ShyNieke** [comment]
Douwsky was so kind to make a shelf model, this will be coming to the mod in an upcoming version
