### ISSUE TITLE
[Bug]: Server crash after placing Vindicator statue, subsequently server crashes on startup

### ISSUE THREAD

**Issue by VansTheMan** [svennieke/StatuesMod#86]
### General Info

- [X] I am running a modpack
- [ ] I can reproduce this issue consistently in single-player
- [X] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [X] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the mod

### Forge version

43.2.6

### Minecraft version

1.19.2

### Mod version

0.3.2.1, 0.3.2.2, 0.3.2.3

### Java version

17.0.2

### Issue Description

Player on the Direwolf20 1.19.2 1.7.0 server placed Vindicator statue, which I believe he had just upgraded.

Server crashed very shortly after placing statue, and subsequently crashed on startup.

Was initially running Statues 0.3.2.1, as that was what was being used in the latest Release version of the modpack. I attempted updating to 0.3.2.3 and also tried 0.3.2.2, but the server crashed on startup with both newer versions as well.

Server did start and remained stable with Statues mod removed.

Thanks for the cool mod! I hope this is helpful. I'm happy to provide any other information which might help.

### Additional Information

Initial crash:
https://pastebin.com/APeXnCW5

Subsequent crashes:
https://pastebin.com/EzkaBzmH
https://pastebin.com/cThwf8Bm
https://pastebin.com/CZSRBRLF
https://pastebin.com/51NtHp1Z

**Comment by Mrbysco** [comment]
This has been fixed in the next build which has been uploaded to CurseForge

**Comment by Mrbysco** [comment]
https://www.curseforge.com/minecraft/mc-mods/statues/files/4506453
