### ISSUE TITLE
[Suggestion]: Alex’s Mobs Support

### ISSUE THREAD

**Issue by AuraNyxe** [svennieke/StatuesMod#88]
### General Info

- [X] I would like to propose new content
- [ ] I would like to propose changes
- [ ] I would like to propose another thing

### Suggestion Description

Any chance you would be able to or want to add support for Alex’s Mobs? I love your mod and I want more statues lol

**Comment by ShyNieke** [comment]
Currently I am still adding all Vanilla mobs, I can't tell you yet which mods I will add support for in the future as all models and textures are hand made.

That said I will keep the suggestion under consideration for once I am done with vanilla.
Will close the issue but know that I won't forget about the suggestion
