### ISSUE TITLE
[Bug]: Statue doesn't track kills while in Curio slot

### ISSUE THREAD

**Issue by NekoLeila** [svennieke/StatuesMod#93]
### General Info

- [ ] I am running a modpack
- [X] I can reproduce this issue consistently in single-player
- [ ] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [ ] I am using the latest version of the mod

### Forge version

47.1.3

### Minecraft version

1.20.1

### Mod version

0.3.6.4

### Java version

I don't know

### Issue Description

Put statue in inventory, it tracks kills, put statue into curio slot, it no longer tracks kills.

**Comment by Mrbysco** [comment]
That's not a bug, curios slots are not seen as part of the inventory
