### ISSUE TITLE
[Bug]: Ticking Entity crashes server when using blaze statue to kill blazes

### ISSUE THREAD

**Issue by TheNuclei** [svennieke/StatuesMod#95]
### General Info

- [X] I am running a modpack
- [ ] I can reproduce this issue consistently in single-player
- [X] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [X] I am crashing and can provide my crash report(s)
- [ ] I am using the latest version of the mod

### Forge version

47.2.18

### Minecraft version

1.20.1

### Mod version

0.3.6.5

### Java version

Java 8 1.8.0_312 / Java 17 17.0.1 2021-10-19 ( Build 17.0.1+12)

### Issue Description

Modpack in use: Chosen's Modded Adventure 0.6.1.

Using a Killing 2, Looting 1 blaze statue next to a blaze spawner causes a ticking entity crash. Attached is a crash dump from the server. Using the looting function on it's own does not crash.

### Additional Information

https://pastebin.com/QnKkXDDk

**Comment by Mrbysco** [comment]
Do you by chance have a reliquary item in your curios?

**Comment by TheNuclei** [comment]
I do not. My equipped curios are:
Iron Gloves from The Aether
Engineer's Goggles from Create
Diamond Backpack from Sophisticated Backpacks
Lucky Rock from Majrusz's accessories.

As for standard armor and such a mix of diamond and chainmail that have randomized effects from Apotheosis.

**Comment by agreedSkiing** [comment]
Adding to this issue just tried this with the Chosen's modded Adventure pack and only updated the statues mod to 4.0.1 and created a zombie killer statue I and nothing happened, my single player world didn't crash, upgraded it to second level and the minecraft client crashed. Same thing happens with the killer 3 statue

Can't include the zip since it is to large for github uploads :/

------
P.S. My version of the modpack also includes https://www.curseforge.com/minecraft/mc-mods/spice-of-life-carrot-edition

**Comment by ShyNieke** [comment]
without a crash log we can't debug this, please provide the crash log

**Comment by agreedSkiing** [comment]
[crash.log](https://github.com/ShyNieke/StatuesMod/files/14229662/crash.log)

---
[Rejoin-crash.log](https://github.com/ShyNieke/StatuesMod/files/14229678/crash.log)

**Comment by Mrbysco** [comment]
All these crashlogs have one thing in common. They all crash when Reliquary is trying to check if the player has an item that stops targeting.

**Comment by Mrbysco** [comment]
At best it can be a problem with the fake player trying to hurt the mob... but then it'd be an oversight on the mod not checking if the player they're checking is a fakeplayer

**Comment by agreedSkiing** [comment]
But why does this not happen if killer 1 is used?

**Comment by Mrbysco** [comment]
Because it only starts using a fake player on a higher killer tier as higher tiers drop player drops which requires a fake player

**Comment by Mrbysco** [comment]
Uploading a new version that should hopefully fix the nullpointer

**Comment by agreedSkiing** [comment]
Damn it hoped that 4.0.2 would fix it or do I need to recreate my creative world for it?
[crash.log](https://github.com/ShyNieke/StatuesMod/files/14231679/crash.log)

P.S. Should not have named my prism instance Statues 4.0.1...

**Comment by agreedSkiing** [comment]
Adding my export of the modpack to help with this issue https://drive.google.com/file/d/1z7bhwH_TTKoyJfEeRejl_5rDuENzDTgP/view?usp=sharing

**Comment by Mrbysco** [comment]
The next version should fix this for good 😓 If not I'll reopen the issue

**Comment by agreedSkiing** [comment]
> The next version should fix this for good 😓 If not I'll reopen the issue

Just tried it and it works :+1:
