### ISSUE TITLE
[Bug]: S.T.A.T.U.E doesnt drop inventory when broken

### ISSUE THREAD

**Issue by Gaz492** [svennieke/StatuesMod#99]
### General Info

- [ ] I am running a modpack
- [X] I can reproduce this issue consistently in single-player
- [ ] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the mod

### Forge version

neo 21.1.92

### Minecraft version

1.21.1

### Mod version

0.4.15

### Java version

21

### Issue Description

Breaking a S.T.A.T.U.E with a statue(es) inside of it won't drop them, it just deletes them.

Steps to reproduce

1. Place S.T.A.T.U.E
2. Insert any statue
3. Break S.T.A.T.U.E
4. Observe no statues drop, only the S.T.A.T.U.E is returned
[](https://github.com/FTBTeam/FTB-Modpack-Issues/issues/6522)

**Comment by Mrbysco** [comment]
Will look into when I get home
